### ISSUE TITLE
As developers we need to learn/ install Node.js React.js Express MongoDB 

### ISSUE THREAD

**Issue by derekh2699** [nyu-software-engineering/teach-me#6]
## Estimate of Work
L

## Acceptance Criteria
- [x] Installed Node.js and learnt basic commands
- [x] Installed React.js and learnt basic commands
- [x] Installed Express and learnt basic commands
- [x] Installed MongoDB and learnt basic commands
- [x] Gained high-level understanding of MERN stack

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-teach-me - this is a spike, not a user story.  Please fix the label.
