### ISSUE TITLE
As a learner, I want to comment on my instructor after completing the course 

### ISSUE THREAD

**Issue by JunyangMa** [nyu-software-engineering/teach-me#9]
## Acceptance Criteria
- [ ] There is a textbox for the learner to type in the comment on the rating page
- [ ] Click the submit button to submit the comment

## Estimate of work
M

**Comment by haomiao-han** [comment]
Note: As of 5/18, this User Story is deprecated in favor of learners providing comments to specific classes, instead of instructors.
